#!/usr/bin/env bash

DOTFILES=(
    .aliases
    .bash_logout
    .bash_profile
    .bash_prompt
    .bashrc
    .curlrc
    .editorconfig
    .emacs.d
    .exports
    .functions
    .gdbinit
    .gitattributes
    .gitconfig
    .gitignore
    .gvimrc
    .hgignore
    .hushlogin
    .inputrc
    .profile
    .screenrc
    .ssh
    .tmux.conf
    .vim
    .vimrc
    .wgetrc
)

UTILS=(
    coreutils
    moreutils
    gnu-sed
    gnu-tar
    gnu-indent
    gnu-which
    grep
    findutils
    gnupg
)

BREWAPPS=(
    python
    python2
)

CASKAPPS=(
    google-chrome
    google-backup-and-sync
    marshallofsound-google-play-music-player
    emacs
    sketchup-pro
    whatsapp
)

revoke_sudo () {
    echo -n Revoking sudo privileges....
    sudo -- sh -c \
           "rm -f /etc/sudoers.d/wheel; dscl /Local/Default -delete /Groups/wheel GroupMembership $(whoami)"
    echo Log out then back in for changes to take effect
}

grant_sudo() {
    echo Granting sudo privileges....

    trap revoke_sudo EXIT

    printf "%s\n" "%wheel ALL=(ALL) NOPASSWD: ALL" | \
        sudo tee "/etc/sudoers.d/wheel" > /dev/null && \
        sudo dscl /Local/Default append /Groups/wheel GroupMembership "$(whoami)"
}

do_ssh() {
    ssh-keygen
    eval $(ssh-agent -s)
#    ssh-add
}

function do_repo() {
    cd ~
    softwareupdate --install --all
    xcode-select --install
    git clone git@github.com:careyjung/dotfiles.git
    ssh-keygen
}

function do_brew() {
    echo "Installing/updating brew..."
    
    if [ ! `which brew` ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew update
    brew upgrade
}

function do_utils() {
    echo Installing utils...
    for pkg in ${UTILS[@]}; do
        brew install $pkg --with-default-names
    done
}

function do_bash() {
    echo Installing bash and bash-completion2...
    brew install bash bash-completion2
    if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
        echo '/usr/local/bin/bash' | sudo tee -a /etc/shells
        chsh -s /usr/local/bin/bash;
    fi
}

function do_dotfiles() {
    echo Installing dotfiles: ${DOTFILES[@]}
    rsync -avh --no-perms ${DOTFILES[@]} ~
    (cd ~; source ~/.bash_profile)
}

function do_brewapps() {
    echo Installing brew apps: ${BREWAPPS[@]}
    brew install ${BREWAPPS[@]}
}

function do_caskapps() {
    echo Installing brew cask apps: ${CASKAPPS[@]}
    for app in ${CASKAPPS[@]}; do
        brew cask install $app
    done
}

function do_system() {
    echo Installing system preferences...

    # Dock Preferences
    # Hot corners:
    #  0: no-op
    #  2: Mission Control
    #  3: Show application windows
    #  4: Desktop
    #  5: Start screen saver
    #  6: Disable screen saver
    #  7: Dashboard
    # 10: Put display to sleep
    # 11: Launchpad
    # 12: Notification Center
    # 'tr' = top right, 'br' = bottom right, etc.
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock wvous-tr-corner -int 2
    defaults write com.apple.dock wvous-tr-modifier -int 0
    defaults write com.apple.dock wvous-br-corner -int 10
    defaults write com.apple.dock wvous-br-modifier -int 0
    defaults write com.apple.dock wvous-bl-corner -int 4
    defaults write com.apple.dock wvous-bl-modifier -int 0			
    defaults write com.apple.dock minimize-to-application -bool true
    killall Dock

    # Finder Preferences:
    # - hide files from Desktop
    # - add Quit menu item: ⌘ + Q will also hide desktop icons
    defaults write com.apple.finder CreateDesktop false
    defaults write com.apple.finder QuitMenuItem -bool true
    killall Finder

    # nvram Preferences:
    # - silent boot (unreliable)
    sudo nvram SystemAudioVolume=" "
    
    # screensaver prefs
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay 1200
    defaults write com.apple.screensaver idleTime 120
    defaults read com.apple.screensaver >/dev/null
    osascript -e 'tell application "System Preferences" to quit'


    # Device Preferences
    defaults write NSGlobalDomain KeyRepeat -int 2				# fast repeat
    defaults write NSGlobalDomain InitialKeyRepeat -int 15			# no delay
    defaults write NSGlobalDomain com.apple.trackpad.scaling -int 3		# fast tracking
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true # tap to click
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
}

function do_terminal() {
    echo Installing Terminal preferences...

    cp init/com.apple.Terminal.plist ~/Library/Preferences

    # Force Terminal to flush its cache (supposedly)
    defaults read com.apple.Terminal>/dev/null 
}


CALLS=(ssh brew utils bash dotfiles brewapps caskapps system terminal)

if [ $# -gt 0 ]; then
    CALLS=()
    CALLS=$@
fi

grant_sudo # revoked on exit

setup_ssh

for call in ${CALLS[@]}; do
    do_${call}
done

exit 0
