#!/usr/bin/env bash

cd ~

if [ ! `which brew` ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew update
brew upgrade
brew install git

if [ ! -f ~/.ssh/id_rsa.pub ]; then
    ssh-keygen
    echo >~/.ssh/config <<EOF
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/id_rsa
EOF
    eval $(ssh-agent -s)
    ssh-add -K
fi
cat ~/.ssh/id_rsa.pub
read -p "Please add the above ssh public key to github->settings. Press any key when done. I'll wait..."

git clone git@github.com:careyjung/dotfiles.git

./setup

exit 0
